// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupToWebdav():Promise<Record<string, any>>;

export function CompressItem(arg1:string,arg2:string):Promise<void>;

export function ConnectSSH(arg1:string,arg2:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<boolean>;

export function DeleteItem(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function GetConnections():Promise<Array<main.Connection>>;

export function GetWebdavConfig():Promise<Record<string, string>>;

export function IsPortableVersion():Promise<boolean>;

export function ListDir(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function ListWebdavBackups():Promise<Array<Record<string, any>>>;

export function Mkdir(arg1:string,arg2:string):Promise<void>;

export function PingServer(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function ReadPrivateKeyFile():Promise<string>;

export function RenameItem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestoreFromWebdavFile(arg1:string):Promise<Record<string, any>>;

export function SaveConnection(arg1:main.Connection):Promise<main.Connection>;

export function SaveWebdavConfig(arg1:Record<string, string>):Promise<void>;

export function SystemInfo(arg1:string):Promise<Record<string, any>>;

export function TestWebdavConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UncompressItem(arg1:string,arg2:string):Promise<void>;

export function UpdateApp(arg1:string,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
