// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupToWebdav() {
  return window['go']['main']['App']['BackupToWebdav']();
}

export function CompressItem(arg1, arg2) {
  return window['go']['main']['App']['CompressItem'](arg1, arg2);
}

export function ConnectSSH(arg1, arg2) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteItem'](arg1, arg2, arg3);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetWebdavConfig() {
  return window['go']['main']['App']['GetWebdavConfig']();
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function ListWebdavBackups() {
  return window['go']['main']['App']['ListWebdavBackups']();
}

export function Mkdir(arg1, arg2) {
  return window['go']['main']['App']['Mkdir'](arg1, arg2);
}

export function PingServer(arg1, arg2) {
  return window['go']['main']['App']['PingServer'](arg1, arg2);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function ReadPrivateKeyFile() {
  return window['go']['main']['App']['ReadPrivateKeyFile']();
}

export function RenameItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameItem'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestoreFromWebdavFile(arg1) {
  return window['go']['main']['App']['RestoreFromWebdavFile'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveWebdavConfig(arg1) {
  return window['go']['main']['App']['SaveWebdavConfig'](arg1);
}

export function SystemInfo(arg1) {
  return window['go']['main']['App']['SystemInfo'](arg1);
}

export function TestWebdavConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestWebdavConnection'](arg1, arg2, arg3);
}

export function UncompressItem(arg1, arg2) {
  return window['go']['main']['App']['UncompressItem'](arg1, arg2);
}

export function UpdateApp(arg1) {
  return window['go']['main']['App']['UpdateApp'](arg1);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2, arg3);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
